author:             "Your name"
base_url:           "http://your.site.url"
buzz:               "A Monochromatic Space"
disqus_shortname: 
markdown:           redcarpet
paginate:           1
paginate_path:      /page/:num/index.html
permalink:          /:year/:month/:day/:title.html
highlighter:        pygments
site_name:          "Subfusc"

navs:
  - title: Archives
    href: /archives.html
  - title: About
    href: /about.html
  - title: RSS
    href: /rss.xml